# simplers/configs/config.yaml
mongodb:
  uri: "mongodb://10.196.18.3:27017" # 실제 MongoDB URI
  db_name: "your_database_name"    # 실제 DB 이름
  # options:
  #   maxPoolSize: 200

opensearch:
  hosts: ["http://10.196.18.3:9200"] # 실제 OpenSearch 호스트
  http_auth:
    user: 'admin'
    password: 'Test0365' # 실제 비밀번호

api_security:
  api_key: "YOUR_SECRET_API_KEY" # 실제 사용할 보안 API 키

# --- Oracle DB 설정 추가 ---
oracledb:
  user: "your_oracle_user"
  password: "your_oracle_password"
  dsn: "your_oracle_host:1521/your_service_name"
  encoding: "UTF-8"
  pool_min: 2
  pool_max: 10
  pool_increment: 1
  pool_timeout: 60


# --- 배치 스코어링 설정 추가 ---
batch_scoring:
  source_weights: # 소스 기반 점수 가중치
    global: 0.3   # 예시 가중치 조정
    cluster: 0.5  # 예시 가중치 조정
    local: 1.0    # 예시 가중치 조정
    other: 0.2    # 기타 후보 가중치
  cf_weight: 0.6      # CF 점수 가중치 (예시)
  cb_weight: 0.4      # CB 점수 가중치 (예시)
  min_score_threshold: 0.01 # 최종 점수 임계값 (예시)
  max_candidates_per_user: 500 # 사용자별 최대 후보 수 (예시)
  # CB 관련 설정 (예시)
  cb_tfidf_fields: ["title", "btopic", "stopic"] # TF-IDF 계산에 사용할 필드
  cb_user_history_limit: 50 # 사용자 프로필 생성 시 사용할 최근 상호작용 수
  # CF 관련 설정 (예시)
  cf_item_similarity_metric: "jaccard" # 또는 "cosine"
  cf_user_history_limit: 100 # 아이템 추천 시 참고할 사용자 최근 상호작용 수
  cf_min_co_occurrence: 2 # 아이템 유사도 계산 시 최소 동시 등장 횟수 (Jaccard/Cosine 용)

# --- 룰 설정 ---
rules:
  global_stock_top_return:
    top_n: 10
    allowed_countries: ["Korea", "USA"]
    days_back: 3
    max_abs_return: 50
  global_top_liked_content:
    default_top_n: 50
    max_top_n: 1000
