# simplers/configs/config.yaml
mongodb:
  uri: "mongodb://localhost:27017" # 실제 MongoDB URI
  db_name: "your_database_name"    # 실제 DB 이름
  # options:
  #   maxPoolSize: 200

opensearch:
  hosts: ["http://10.196.18.3:9200"] # 실제 OpenSearch 호스트
  http_auth:
    user: 'admin'
    password: 'Test0365' # 실제 비밀번호

api_security:
  api_key: "YOUR_SECRET_API_KEY" # 실제 사용할 보안 API 키

# --- Oracle DB 설정 추가 ---
oracledb:
  user: "your_oracle_user"
  password: "your_oracle_password"
  # DSN 방식 예시 (host, port, service_name 포함)
  dsn: "your_oracle_host:1521/your_service_name"
  # 또는 개별 파라미터 방식
  # host: "your_oracle_host"
  # port: 1521
  # service_name: "your_service_name" # 또는 sid: "your_oracle_sid"
  encoding: "UTF-8" # 필요시 인코딩 지정
  # --- Connection Pool 설정 (선택 사항) ---
  pool_min: 2  # 최소 풀 사이즈
  pool_max: 10 # 최대 풀 사이즈
  pool_increment: 1 # 증가 단위
  pool_timeout: 60 # 풀에서 연결 대기 시간 (초)
  # Oracle Client 초기화 필요시 (Thick 모드) - 경로 지정
  # client_lib_dir: "/path/to/your/instantclient_XX_Y"


# --- 배치 스코어링 설정 추가 ---
batch_scoring:
  source_weights: # 소스 기반 점수 가중치
    global: 0.3   # 예시 가중치 조정
    cluster: 0.5  # 예시 가중치 조정
    local: 1.0    # 예시 가중치 조정
  cf_weight: 0.6      # CF 점수 가중치 (예시)
  cb_weight: 0.4      # CB 점수 가중치 (예시)
  min_score_threshold: 0.01 # 최종 점수 임계값 (예시)
  max_candidates_per_user: 500 # 사용자별 최대 후보 수 (예시)
  # CB 관련 설정 (예시)
  cb_tfidf_fields: ["title", "btopic", "stopic"] # TF-IDF 계산에 사용할 필드
  cb_user_history_limit: 50 # 사용자 프로필 생성 시 사용할 최근 상호작용 수
  # CF 관련 설정 (예시)
  cf_item_similarity_metric: "jaccard" # 또는 "cosine"
  cf_user_history_limit: 100 # 아이템 추천 시 참고할 사용자 최근 상호작용 수
  cf_min_co_occurrence: 2 # 아이템 유사도 계산 시 최소 동시 등장 횟수 (Jaccard/Cosine 용)